### ISSUE TITLE
Raspberry Bad display name "" local or ssh

### ISSUE THREAD

**Issue by fricou** [moses-palmer/pynput#123]
Hi, I have an issue with "from pynput import keyboard".

It is work great on Windows but when I use the script on a Raspberry it don't work.
This is the error message : 

```
Traceback (most recent call last):
  File "ctrl_keybord.py", line 1, in <module>
    from pynput import keyboard
  File "/home/pi/.local/lib/python2.7/site-packages/pynput/__init__.py", line 23, in <module>
    from . import keyboard
  File "/home/pi/.local/lib/python2.7/site-packages/pynput/keyboard/__init__.py", line 49, in <module>
    from ._xorg import KeyCode, Key, Controller, Listener
  File "/home/pi/.local/lib/python2.7/site-packages/pynput/keyboard/_xorg.py", line 39, in <module>
    from pynput._util.xorg import (
  File "/home/pi/.local/lib/python2.7/site-packages/pynput/_util/xorg.py", line 40, in <module>
    _check()
  File "/home/pi/.local/lib/python2.7/site-packages/pynput/_util/xorg.py", line 38, in _check
    display = Xlib.display.Display()
  File "/home/pi/.local/lib/python2.7/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/home/pi/.local/lib/python2.7/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/home/pi/.local/lib/python2.7/site-packages/Xlib/protocol/display.py", line 85, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "/home/pi/.local/lib/python2.7/site-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
  File "/home/pi/.local/lib/python2.7/site-packages/Xlib/support/unix_connect.py", line 61, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""
```
I use Python 2.7.13

Thanks for your help !
Florian

**Comment by moses-palmer** [comment]
*pynput* uses *Xlib* to send and receive input events. Xlib requires the environment variable `DISPLAY` to be set. It will be set for all processes started in your desktop environment, but not when SSH'ing into the machine.

Make sure to set `DISPLAY` when launching the script: `DISPLAY=":0" python ctrl_keyboard.py`. The actual value to use can be retrieved by running `echo $DISPLAY` when logged into the desktop environment.

If you don't have an X server running---I have none on my *Raspberry Pi*---unfortunately you cannot use *pynput*.
