### ISSUE TITLE
No module named 'Quartz' on Windows

### ISSUE THREAD

**Issue by Stantl3r** [moses-palmer/pynput#181]
When I try and check on mouse load a list of mouse events, I get this error on my Windows 10 machine. Any advice?

`Traceback (most recent call last):
  File "server.py", line 46, in <module>
    mouse_clicks = pickle.loads(pickled_clicks)
  File "C:\Users\Stanley\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pynput\mouse\_darwin.py", line 28, in <module>
    import Quartz
ModuleNotFoundError: No module named 'Quartz'`

**Comment by Stantl3r** [comment]
Nevermind, it looks like pickle was the problem here. After switching to json, everything started working fine.
