### ISSUE TITLE
keyboard controller error in python3.8

### ISSUE THREAD

**Issue by rearyx** [moses-palmer/pynput#188]
Are there any new features that are causing errors

```
Traceback (most recent call last):
  File "/Users/catmeat/forchange/personal/mygui/myautogui.py", line 6, in <module>
    keyboard.press(Key.space)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pynput/keyboard/_base.py", line 379, in press
    self._handle(resolved, True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pynput/keyboard/_darwin.py", line 140, in _handle
    (key if key not in Key else key.value)._event(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/enum.py", line 310, in __contains__
    raise TypeError(
TypeError: unsupported operand type(s) for 'in': 'KeyCode' and 'EnumMeta'
```

**Comment by rearyx** [comment]
It can be easily reproduced through the documentation tutorial

**Comment by moses-palmer** [comment]
Thank you for your report.

It appears that this error was not corrected in the *macOS* code. I just release version 1.4.5; can you please test it? Unfortunately, I no longer have access to a modern macOS system.

**Comment by moses-palmer** [comment]
Due to lack of feedback, I will close this issue.
