### ISSUE TITLE
I'm getting "ValueError: {'is_media': True}" when trying to import pynput

### ISSUE THREAD

**Issue by ah3243** [moses-palmer/pynput#198]
I'm getting this value error after installing through pip on a clean conda environment(i've tried python 3.5, 3.6 and 3.7 all on OSX 10.15. 

It was working before so i built my script around it then for some reason started throwing up this error, which was frustrating. Any help you could give me would be amazing. Here's the full stacktrace. 

>>> import pynput
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alberthiggins/anaconda3/envs/newMouseTest/lib/python3.5/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/Users/alberthiggins/anaconda3/envs/newMouseTest/lib/python3.5/site-packages/pynput/keyboard/__init__.py", line 40, in <module>
    from ._darwin import KeyCode, Key, Controller, Listener
  File "/Users/alberthiggins/anaconda3/envs/newMouseTest/lib/python3.5/site-packages/pynput/keyboard/_darwin.py", line 115, in <module>
    class Key(enum.Enum):
  File "/Users/alberthiggins/anaconda3/envs/newMouseTest/lib/python3.5/site-packages/pynput/keyboard/_darwin.py", line 166, in Key
    media_play_pause = KeyCode.from_vk(NX_KEYTYPE_PLAY, is_media=True)
  File "/Users/alberthiggins/anaconda3/envs/newMouseTest/lib/python3.5/site-packages/pynput/keyboard/_base.py", line 131, in from_vk
    return cls(vk=vk, **kwargs)
  File "/Users/alberthiggins/anaconda3/envs/newMouseTest/lib/python3.5/site-packages/pynput/keyboard/_base.py", line 62, in __init__
    raise ValueError(kwargs)
ValueError: {'is_media': True}

**Comment by moses-palmer** [comment]
Thank you for your report!

It seems that the media key handling feature introduced in _pynput 1.5.0_ was incorrectly implemented for _macOS_. I have made a quick release of _pynput 1.5.1_ to fix this; I still do not have access to a working _Apple_ system, so I have unfortunately not been able to test it.

Does updating to _pynput 1.5.1_ solve the problem?

**Comment by ah3243** [comment]
Hey yep it's working! Incredible, thank you so much for your speedy response!
