### ISSUE TITLE
keyboard.GlobalHotKeys and keyboard.HotKey are not working.

### ISSUE THREAD

**Issue by microrepar** [moses-palmer/pynput#206]
Hi guys!
I am trying to run the following code, but I was unsuccessfull.
I wold like to know what I am doing wrong!

```
from pynput import keyboard
def on_activate_h():
    print('<ctrl>+<alt>+h pressed')
def on_activate_i():
    print('<ctrl>+<alt>+i pressed')
with keyboard.GlobalHotKeys({
        '<ctrl>+<alt>+h': on_activate_h,
        '<ctrl>+<alt>+i': on_activate_i}) as h:
    h.join()
```

```
Unhandled exception in listener callback
Traceback (most recent call last):
  File "C:\Users\m.c.silva\Envs\rpa-python-env\lib\site-packages\pynput\_util\__init__.py", line 162, in inner
    return f(self, *args, **kwargs)
  File "C:\Users\m.c.silva\Envs\rpa-python-env\lib\site-packages\pynput\_util\win32.py", line 382, in _handler
    converted = self._convert(code, msg, lpdata)
  File "C:\Users\m.c.silva\Envs\rpa-python-env\lib\site-packages\pynput\keyboard\_win32.py", line 244, in _convert
    if self._event_filter(msg, data) is False:
AttributeError: 'GlobalHotKeys' object has no attribute '_event_filter'
Traceback (most recent call last):
  File "E:\rpa-py\teste_hotkeys.py", line 15, in <module>
    h.join()
  File "C:\Users\m.c.silva\Envs\rpa-python-env\lib\site-packages\pynput\_util\__init__.py", line 210, in join
    six.reraise(exc_type, exc_value, exc_traceback)
  File "C:\Users\m.c.silva\Envs\rpa-python-env\lib\site-packages\six.py", line 695, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\m.c.silva\Envs\rpa-python-env\lib\site-packages\pynput\_util\__init__.py", line 162, in inner
    return f(self, *args, **kwargs)
  File "C:\Users\m.c.silva\Envs\rpa-python-env\lib\site-packages\pynput\_util\win32.py", line 382, in _handler
    converted = self._convert(code, msg, lpdata)
  File "C:\Users\m.c.silva\Envs\rpa-python-env\lib\site-packages\pynput\keyboard\_win32.py", line 244, in _convert
    if self._event_filter(msg, data) is False:
AttributeError: 'GlobalHotKeys' object has no attribute '_event_filter'
```

**Comment by moses-palmer** [comment]
Thank you for your report!

This is a known issue with *pynput 1.6.0*. I just released version *1.6.1* with a fix. Please reopen this issue is your find that updating does not resolve your problem.
