### ISSUE TITLE
Need help with starting two listeners simultaneously

### ISSUE THREAD

**Issue by Peter-Schorn** [moses-palmer/pynput#209]
I've written the following code, which listens for a command+delete hotkey:
```
def on_activate():
    global query
    print('cmd+del activated!')
    query = '' # those are two single quotes, not one double quote

with keyboard.GlobalHotKeys(
        {'<cmd>+<backspace>' or '<cmd_r>+<backspace>': on_activate}) as h: h.join()
```
I also have a listener that records alphanumeric characters:
```
def on_press(key):
    global query
    try: query += key.char

query = ''
with keyboard.Listener(on_press) as listener: listener.join()
```
How do I run these sections of code simultaneously?

**Comment by moses-palmer** [comment]
You can run multiple listeners as multiple contexts:

```python
from pynput import keyboard

def on_activate():
    pass # Your activation callback

def on_press(key):
    pass # Your listener callback

with with keyboard.GlobalHotKeys({}) as g, keyboard.Listener(on_press) as l:
    g.join()
    l.join()
```

**Comment by Peter-Schorn** [comment]
I just tried that, but I got a bunch of error messages. Here's my code.
```
import os, re, spotipy, spotipy.util as util, time, threading
from pynput import keyboard

def on_activate():
    global query
    print('cmd+del activated!')
    query = ''
    print(query)


def on_press(key):
    global query

    if str(key) == 'Key.esc': query = ''; return

    try: query += key.char
    except:
        if str(key) == 'Key.backspace': query = query[:-1]

    if query.isspace(): query = ''

    print(query)

query = ''

with keyboard.GlobalHotKeys({'<cmd>+<backspace>': on_activate}) as g, keyboard.Listener(on_press) as l:
    g.join()
    l.join()
```
And's here's the error output.
```
Unhandled exception in listener callback
Traceback (most recent call last):
  File "/Users/pschorn/PycharmProjects/SpotifyIndex/venv2/lib/python3.7/site-packages/pynput/_util/__init__.py", line 162, in inner
    return f(self, *args, **kwargs)
  File "/Users/pschorn/PycharmProjects/SpotifyIndex/venv2/lib/python3.7/site-packages/pynput/_util/darwin.py", line 261, in _handler
    self._handle(proxy, event_type, event, refcon)
  File "/Users/pschorn/PycharmProjects/SpotifyIndex/venv2/lib/python3.7/site-packages/pynput/keyboard/_darwin.py", line 237, in _handle
    key = self._event_to_key(event)
  File "/Users/pschorn/PycharmProjects/SpotifyIndex/venv2/lib/python3.7/site-packages/pynput/keyboard/_darwin.py", line 281, in _event_to_key
    vk = Quartz.CGEventGetIntegerValueField(
  File "/Users/pschorn/PycharmProjects/SpotifyIndex/venv2/lib/python3.7/site-packages/objc/_lazyimport.py", line 207, in __getattr__
    raise AttributeError(name)
AttributeError: CGEventGetIntegerValueField
Traceback (most recent call last):
  File "/Users/pschorn/PycharmProjects/SpotifyIndex/Keyboard.py", line 32, in <module>
    g.join()
  File "/Users/pschorn/PycharmProjects/SpotifyIndex/venv2/lib/python3.7/site-packages/pynput/_util/__init__.py", line 210, in join
    six.reraise(exc_type, exc_value, exc_traceback)
  File "/Users/pschorn/PycharmProjects/SpotifyIndex/venv2/lib/python3.7/site-packages/six.py", line 695, in reraise
    raise value.with_traceback(tb)
  File "/Users/pschorn/PycharmProjects/SpotifyIndex/venv2/lib/python3.7/site-packages/pynput/_util/__init__.py", line 162, in inner
    return f(self, *args, **kwargs)
  File "/Users/pschorn/PycharmProjects/SpotifyIndex/venv2/lib/python3.7/site-packages/pynput/_util/darwin.py", line 261, in _handler
    self._handle(proxy, event_type, event, refcon)
  File "/Users/pschorn/PycharmProjects/SpotifyIndex/venv2/lib/python3.7/site-packages/pynput/keyboard/_darwin.py", line 237, in _handle
    key = self._event_to_key(event)
  File "/Users/pschorn/PycharmProjects/SpotifyIndex/venv2/lib/python3.7/site-packages/pynput/keyboard/_darwin.py", line 281, in _event_to_key
    vk = Quartz.CGEventGetIntegerValueField(
  File "/Users/pschorn/PycharmProjects/SpotifyIndex/venv2/lib/python3.7/site-packages/objc/_lazyimport.py", line 207, in __getattr__
    raise AttributeError(name)
AttributeError: CGEventGetIntegerValueField
```

Any idea what's happening?
