### ISSUE TITLE
AttributeError: module 'socket' has no attribute 'AF_UNSPEC'

### ISSUE THREAD

**Issue by ayushmankumar7** [moses-palmer/pynput#219]

**Comment by moses-palmer** [comment]
Thank you for your report.

On what platform does this happen? Can you please provide a stack trace?

**Comment by ayushmankumar7** [comment]
Traceback (most recent call last):
  File "keylogger.py", line 2, in <module>
    from pynput.keyboard import Key, Listener
  File "/home/ayushman/.local/lib/python3.7/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/home/ayushman/.local/lib/python3.7/site-packages/pynput/keyboard/__init__.py", line 49, in <module>
    from ._xorg import KeyCode, Key, Controller, Listener
  File "/home/ayushman/.local/lib/python3.7/site-packages/pynput/keyboard/_xorg.py", line 30, in <module>
    import Xlib.display
  File "/home/ayushman/.local/lib/python3.7/site-packages/Xlib/display.py", line 26, in <module>
    from Xlib.protocol import display, request, event, rq
  File "/home/ayushman/.local/lib/python3.7/site-packages/Xlib/protocol/display.py", line 24, in <module>
    import socket
  File "/home/ayushman/Documents/python/TEST/socket.py", line 1, in <module>
    from aiohttp import web
  File "/home/ayushman/.local/lib/python3.7/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "/home/ayushman/.local/lib/python3.7/site-packages/aiohttp/client.py", line 3, in <module>
    import asyncio
  File "/usr/lib/python3.7/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/lib/python3.7/asyncio/base_events.py", line 39, in <module>
    from . import events
  File "/usr/lib/python3.7/asyncio/events.py", line 210, in <module>
    class AbstractEventLoop:
  File "/usr/lib/python3.7/asyncio/events.py", line 313, in AbstractEventLoop
    *, family=socket.AF_UNSPEC,
AttributeError: module 'socket' has no attribute 'AF_UNSPEC'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 21, in <module>
    from urllib.request import urlopen
  File "/usr/lib/python3.7/urllib/request.py", line 88, in <module>
    import http.client
  File "/usr/lib/python3.7/http/client.py", line 71, in <module>
    import email.parser
  File "/usr/lib/python3.7/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/usr/lib/python3.7/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/usr/lib/python3.7/email/_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "/usr/lib/python3.7/email/utils.py", line 29, in <module>
    import socket
  File "/home/ayushman/Documents/python/TEST/socket.py", line 1, in <module>
    from aiohttp import web
  File "/home/ayushman/.local/lib/python3.7/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "/home/ayushman/.local/lib/python3.7/site-packages/aiohttp/client.py", line 3, in <module>
    import asyncio
  File "/usr/lib/python3.7/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/lib/python3.7/asyncio/base_events.py", line 39, in <module>
    from . import events
  File "/usr/lib/python3.7/asyncio/events.py", line 210, in <module>
    class AbstractEventLoop:
  File "/usr/lib/python3.7/asyncio/events.py", line 313, in AbstractEventLoop
    *, family=socket.AF_UNSPEC,
AttributeError: module 'socket' has no attribute 'AF_UNSPEC'

Original exception was:
Traceback (most recent call last):
  File "keylogger.py", line 2, in <module>
    from pynput.keyboard import Key, Listener
  File "/home/ayushman/.local/lib/python3.7/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/home/ayushman/.local/lib/python3.7/site-packages/pynput/keyboard/__init__.py", line 49, in <module>
    from ._xorg import KeyCode, Key, Controller, Listener
  File "/home/ayushman/.local/lib/python3.7/site-packages/pynput/keyboard/_xorg.py", line 30, in <module>
    import Xlib.display
  File "/home/ayushman/.local/lib/python3.7/site-packages/Xlib/display.py", line 26, in <module>
    from Xlib.protocol import display, request, event, rq
  File "/home/ayushman/.local/lib/python3.7/site-packages/Xlib/protocol/display.py", line 24, in <module>
    import socket
  File "/home/ayushman/Documents/python/TEST/socket.py", line 1, in <module>
    from aiohttp import web
  File "/home/ayushman/.local/lib/python3.7/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "/home/ayushman/.local/lib/python3.7/site-packages/aiohttp/client.py", line 3, in <module>
    import asyncio
  File "/usr/lib/python3.7/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/lib/python3.7/asyncio/base_events.py", line 39, in <module>
    from . import events
  File "/usr/lib/python3.7/asyncio/events.py", line 210, in <module>
    class AbstractEventLoop:
  File "/usr/lib/python3.7/asyncio/events.py", line 313, in AbstractEventLoop
    *, family=socket.AF_UNSPEC,
AttributeError: module 'socket' has no attribute 'AF_UNSPEC'

**Comment by moses-palmer** [comment]
This appears to be an import error: does you `$PYTHONPATH` contain `/home/ayushman/Documents/python/TEST`?

In any case, this is unrelated to *pynput*, so I will close this issue.
