### ISSUE TITLE
Error entering Unicode symbols on linux

### ISSUE THREAD

**Issue by JordanLevin** [moses-palmer/pynput#23]
I have this code which attempts to type a backspace and then a unicode symbol when a certain condition is met.
    
    def on_press(key):
        try:
              if key.char == ';':
                  if random.randint(0,20) == 5:
                      keyboard = Controller()
                      keyboard.type(u'\b')
                      keyboard.type(u'\u037E')

However when it tries to type the backspace it gives this error:

Traceback (most recent call last):
  File "input_helper.py", line 105, in <module>
    listener.join()
  File "/home/jordan/.local/lib/python3.5/site-packages/pynput/_util/__init__.py", line 185, in join
    six.reraise(exc_type, exc_value, exc_traceback)
  File "/home/jordan/.local/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/jordan/.local/lib/python3.5/site-packages/pynput/_util/__init__.py", line 140, in inner
    return f(self, *args, **kwargs)
  File "/home/jordan/.local/lib/python3.5/site-packages/pynput/_util/xorg.py", line 427, in _handler
    self._handle(self._display_stop, event)
  File "/home/jordan/.local/lib/python3.5/site-packages/pynput/keyboard/_xorg.py", line 511, in _handle
    self.on_press(key)
  File "/home/jordan/.local/lib/python3.5/site-packages/pynput/_util/__init__.py", line 71, in inner
    if f(*args) is False:
  File "input_helper.py", line 75, in on_press
    keyboard.type(u'\u0008')
  File "/home/jordan/.local/lib/python3.5/site-packages/pynput/keyboard/_base.py", line 448, in type
    self.release(character)
  File "/home/jordan/.local/lib/python3.5/site-packages/pynput/keyboard/_base.py", line 404, in release
    self._handle(resolved, False)
  File "/home/jordan/.local/lib/python3.5/site-packages/pynput/keyboard/_xorg.py", line 196, in _handle
    raise self.InvalidKeyException(key)
pynput.keyboard._base.InvalidKeyException: '\x08'

it gives a similar error for the other unicode character if I remove the backspace so it can get there. This code works on windows but not on linux.

**Comment by moses-palmer** [comment]
Hi,

I have confirmed that your code crashes on *Xorg*, and that it is caused by the unicde character.

The problem is that the character that you want to type does not have a corresponding *X keysym* in [`xorg_keysyms.py`](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/_util/xorg_keysyms.py). That file is generated by the script [`xorg-keysymdef.py`](https://github.com/moses-palmer/pynput/blob/master/tools/xorg-keysymdef.py) using `/usr/include/X11/keysymdef.h` as input. On my system, that file does not define any Coptic letters at all.

All this leads me to think that this cannot be solved, as *Xorg* does not seem to support typing the character.
