### ISSUE TITLE
Sample Code Throws errors.

### ISSUE THREAD

**Issue by Antiswitcher** [moses-palmer/pynput#235]
from pynput import keyboard
with keyboard.Events() as events:
    for event in events:
        if event.key == keyboard.Key.esc:
            break
        else:
            print('Received event {}'.format(event))

#will throw these errors on 3.8 on Ubuntu.

Traceback (most recent call last):
  File "brawl-combo.py", line 9, in <module>
    print('Received event {}'.format(event))
  File "/home/lafont/.local/lib/python3.7/site-packages/pynput/_util/__init__.py", line 225, in __str__
    for (k, v) in vars(self)))
  File "/home/lafont/.local/lib/python3.7/site-packages/pynput/_util/__init__.py", line 225, in <genexpr>
    for (k, v) in vars(self)))
ValueError: too many values to unpack (expected 2)

**Comment by moses-palmer** [comment]
Thank you for your report.

I have updated the event stringification code to iterate over `vars(self).items()`. This will be included in the next release.
