### ISSUE TITLE
Keyboard Event Handler Fail in demo script

### ISSUE THREAD

**Issue by dgm3333** [moses-palmer/pynput#247]
Trying code from the main docs page (as below) fails
Using Win10. pynput install 1.6.8
Tried with : Anaconda : Spyder: Python 3.7
Idle: Python 3.7

Tried with UK and US keyboard settings

The GlobalHotKeys script works fine

This works fine:
```
from pynput.keyboard import Listener
def printIt(key):
    print (key)
with Listener(on_press=printIt) as l:
    l.join()
```

ERROR:
Traceback (most recent call last): 
  File "C:\Users\dgm55\Documents\David\pythonScripts\hotkeys\eventListener.py", line 9, in <module>
    print('Received event {}'.format(event))
  File "C:\Users\dgm55\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pynput\_util\__init__.py", line 225, in __str__
    for (k, v) in vars(self)))
  File "C:\Users\dgm55\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pynput\_util\__init__.py", line 224, in <genexpr>
    '{}={}'.format(k, v)
ValueError: too many values to unpack (expected 2)

CODE: (direct from https://pynput.readthedocs.io/en/latest/)
```
from pynput import keyboard

# The event listener will be running in this block
with keyboard.Events() as events:
    for event in events:
        if event.key == keyboard.Key.esc:
            break
        else:
            print('Received event {}'.format(event))

```

**Comment by moses-palmer** [comment]
Thank you for your report.

This was fixed in commit d7dd43d0c81d5355c51f6010fb44c24aa78a86d6.
