### ISSUE TITLE
Random Hangs using XOrg listener

### ISSUE THREAD

**Issue by cpyles** [moses-palmer/pynput#281]
Using version 1.6.8 of pynput on Manjaro linux.

Exiting a synchronous capture block for keyboard events will randomly fail, causing no more code to execute. I have not tried asynchronous capture or mouse events. 

Example code
```
from pynput import keyboard
def f():
    with keyboard.Events() as events:
        for event in events:
            print(event.key)
            break

while True:
    f()
```
Output when holding down the 'a' key
```
a'a'
aa'a'
aaa'a'
aa'a'
aa'a'
aaa'a'
aa'a'
aa'a'
aaaa'a'
aaaa'a'
aaa'a'
aaa'a'
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```
The output should continue with lines similar to `aa'a'` until you get bored, but, at random intervals, the program will get stuck and do nothing. (to be clear, the program hangs for all keyboard inputs I have tried, not just holding down keys). The interval is anywhere between instant to 20 seconds. Pressing "ctrl+c" will fix the breakage and continue as if it had never gotten stuck.

I have traced the problem to a try except clause in `_util/__init__.py`. Starting from line 407, in class `ListenerMixin`
```
    def _stop_platform(self):
        if not hasattr(self, '_context'):
            self.wait()
        # pylint: disable=W0702; we must ignore errors
        try:
            with display_manager(self._display_stop) as dm:
                dm.record_disable_context(self._context)
        except:
            pass
        # pylint: enable=W0702
```
Removing the clause fixes the problem completely. 

Editing the clause to allow raising a KeyboardInterrupt with the program stuck gvies this traceback
```
a'a'
a'a'
aa'a'
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa^CTraceback (most recent call last):
  File "example.py", line 9, in <module>
    f()
  File "example.py", line 6, in f
    break
  File "/usr/lib/python3.8/site-packages/pynput/_util/__init__.py", line 248, in __exit__
    self._listener.__exit__(*args)
  File "/usr/lib/python3.8/site-packages/pynput/_util/__init__.py", line 129, in __exit__
    self.stop()
  File "/usr/lib/python3.8/site-packages/pynput/_util/__init__.py", line 121, in stop
    self._stop_platform()
  File "/usr/lib/python3.8/site-packages/pynput/_util/xorg.py", line 413, in _stop_platform
    dm.record_disable_context(self._context)
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/lib/python3.8/site-packages/pynput/_util/xorg.py", line 74, in display_manager
    display.sync()
  File "/usr/lib/python3.8/site-packages/Xlib/display.py", line 182, in sync
    self.get_pointer_control()
  File "/usr/lib/python3.8/site-packages/Xlib/display.py", line 833, in get_pointer_control
    return request.GetPointerControl(display = self.display)
  File "/usr/lib/python3.8/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/usr/lib/python3.8/site-packages/Xlib/protocol/rq.py", line 1381, in reply
    self._display.send_and_recv(request = self._serial)
  File "/usr/lib/python3.8/site-packages/Xlib/protocol/display.py", line 561, in send_and_recv
    rs, ws, es = select.select([self.socket], writeset, [], timeout)
KeyboardInterrupt
```

**Comment by moses-palmer** [comment]
Thank you for your report.

Does the following minimal patch fix the error?

```diff
diff --git a/lib/pynput/_util/xorg.py b/lib/pynput/_util/xorg.py
index 72dbd4a..1f60f9f 100644
--- a/lib/pynput/_util/xorg.py
+++ b/lib/pynput/_util/xorg.py
@@ -409,8 +409,7 @@ class ListenerMixin(object):
             self.wait()
         # pylint: disable=W0702; we must ignore errors
         try:
-            with display_manager(self._display_stop) as dm:
-                dm.record_disable_context(self._context)
+            self._display_stop.record_disable_context(self._context)
         except:
             pass
         # pylint: enable=W0702
```

**Comment by PankajKushwaha** [comment]
I was facing same issue.
I made same changed as suggested by moses-palmer, after that issue is not visible. thanks to both of you.

**Comment by frankcrc** [comment]
> Thank you for your report.
> 
> Does the following minimal patch fix the error?
> 
> ```diff
> diff --git a/lib/pynput/_util/xorg.py b/lib/pynput/_util/xorg.py
> index 72dbd4a..1f60f9f 100644
> --- a/lib/pynput/_util/xorg.py
> +++ b/lib/pynput/_util/xorg.py
> @@ -409,8 +409,7 @@ class ListenerMixin(object):
>              self.wait()
>          # pylint: disable=W0702; we must ignore errors
>          try:
> -            with display_manager(self._display_stop) as dm:
> -                dm.record_disable_context(self._context)
> +            self._display_stop.record_disable_context(self._context)
>          except:
>              pass
>          # pylint: enable=W0702
> ```
> 
> Not using the display manager---a wrapper to make errors synchronous---the try-catch clause and _pylint_ warning suppressions could also be removed.

Using version 1.7.5 of pynput on UOS linux.
This patch does work, but in v1.7.5, It seems the issue still exists.
I found 1d986bc9511aceb5 modify related code, but it processes in another way, is this commit for solving this problem?
