### ISSUE TITLE
Odd pynput/xorg/Xlib error (maybe)? Can't use keyboard Listener

### ISSUE THREAD

**Issue by BrianZhang1** [moses-palmer/pynput#284]
I'm trying to make a simple script that clicks around.  I want to make it so it will exit the program when a certain key is pressed. Here is my code:

from pynput.mouse import Button, Controller;
from PIL import ImageGrab;
import time;
from pynput.keyboard import Listener;
import keyboard;

mouse = Controller();

time.sleep(3);

while True:
    mouse.position = (1124, 729);
    mouse.click(Button.left, 1);
    mouse.position = (1001, 1026);
    mouse.click(Button.left, 1);
    time.sleep(1);
    mouse.position = (672,730);
    mouse.click(Button.left, 1);
    mouse.position = (1004, 1009);
    mouse.click(Button.left, 1);
    time.sleep(1);
    battleEndRGB = ImageGrab.grab().load()[995, 802];

I tested it out to see if the import worked, disclaimer it did not. Here is the error I was given when I tried to run the python:
Traceback (most recent call last):
  File "autoMaraPetsBattle.py", line 1, in <module>
    from pynput.mouse import Button, Controller;
  File "/home/brianzhang/.local/lib/python3.8/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/home/brianzhang/.local/lib/python3.8/site-packages/pynput/keyboard/__init__.py", line 52, in <module>
    from ._xorg import KeyCode, Key, Controller, Listener
  File "/home/brianzhang/.local/lib/python3.8/site-packages/pynput/keyboard/_xorg.py", line 39, in <module>
    from pynput._util.xorg import (
  File "/home/brianzhang/.local/lib/python3.8/site-packages/pynput/_util/xorg.py", line 40, in <module>
    _check()
  File "/home/brianzhang/.local/lib/python3.8/site-packages/pynput/_util/xorg.py", line 38, in _check
    display = Xlib.display.Display()
  File "/home/brianzhang/.local/lib/python3.8/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/home/brianzhang/.local/lib/python3.8/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/home/brianzhang/.local/lib/python3.8/site-packages/Xlib/protocol/display.py", line 84, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "/home/brianzhang/.local/lib/python3.8/site-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
  File "/home/brianzhang/.local/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 76, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""

If this isn't a pynput issue, I'm open to any other possibilities, just any help is much appreciated!

**Comment by moses-palmer** [comment]
Thank you for your report.

This behaviour is documented in the [platform limitations](https://pynput.readthedocs.io/en/latest/limitations.html#linux). For use under _Linux_ and _X_, the `DISPLAY` environment variable must be set.

I have updated the backend loading code of *pynput* with improved error messages to help future users.
