### ISSUE TITLE
Error using the "DISPLAY=:0 python -c 'import pynput'" command

### ISSUE THREAD

**Issue by BrianZhang1** [moses-palmer/pynput#286]
This is a continuation of error #284 , where I was directed to follow the instructions on https://pynput.readthedocs.io/en/latest/limitations.html#linux to fix my issue. Using the command: 
DISPLAY=:0 python -c 'import pynput'
Returned another error:

Traceback (most recent call last):
  File "/home/brianzhang/.local/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 119, in get_socket
    s = _get_unix_socket(address)
  File "/home/brianzhang/.local/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 98, in _get_unix_socket
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brianzhang/.local/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 123, in get_socket
    s = _get_tcp_socket(host, dno)
  File "/home/brianzhang/.local/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 93, in _get_tcp_socket
    s.connect((host, 6000 + dno))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/brianzhang/.local/lib/python3.8/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/home/brianzhang/.local/lib/python3.8/site-packages/pynput/keyboard/__init__.py", line 52, in <module>
    from ._xorg import KeyCode, Key, Controller, Listener
  File "/home/brianzhang/.local/lib/python3.8/site-packages/pynput/keyboard/_xorg.py", line 39, in <module>
    from pynput._util.xorg import (
  File "/home/brianzhang/.local/lib/python3.8/site-packages/pynput/_util/xorg.py", line 40, in <module>
    _check()
  File "/home/brianzhang/.local/lib/python3.8/site-packages/pynput/_util/xorg.py", line 38, in _check
    display = Xlib.display.Display()
  File "/home/brianzhang/.local/lib/python3.8/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/home/brianzhang/.local/lib/python3.8/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/home/brianzhang/.local/lib/python3.8/site-packages/Xlib/protocol/display.py", line 89, in __init__
    self.socket = connect.get_socket(name, protocol, host, displayno)
  File "/home/brianzhang/.local/lib/python3.8/site-packages/Xlib/support/connect.py", line 87, in get_socket
    return mod.get_socket(dname, protocol, host, dno)
  File "/home/brianzhang/.local/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 127, in get_socket
    raise error.DisplayConnectionError(dname, str(val))
Xlib.error.DisplayConnectionError: Can't connect to display ":0": [Errno 111] Connection refused

Something I noticed was that when I split the command into two separate commands (DISPLAY=:0 and python -c 'import pynput'), setting the DISPLAY value returned nothing, but the second command returned the error shown above. Is this an error with my X server or something?

**Comment by moses-palmer** [comment]
I have updated the instructions, and they should come lime soon.

The relevant new section is

> Please note that the value `DISPLAY=:0` is just an example. To find the
> actual value, please launch a terminal application from your desktop
> environment and issue the command `echo $DISPLAY`.

I will close this issue, as it is not related to *pynput*.

**Comment by BrianZhang1** [comment]
I understand this is not an issue related to input, but I have no idea where to go from here. I'm running wsl on windows with an ubuntu terminal, so I don't have any GUI and there is no DISPLAY value. I don't know what to set the value to in order for it to work. I've searched the internet for hours, but can't find anything, and to be honest, I'm getting a little desperate. Do you have any advice for next steps?

**Comment by moses-palmer** [comment]
Ah, that explains a lot!

I don't think you could get pynput to work reasonably well under WSL; in
that case, you would have to launch an X server under WSL, and you would
only be able to interact with other applications launched under WSL in the
same X session.

For your use case, I strongly encourage you to run your application under
the host operating system, Windows.

**Comment by BrianZhang1** [comment]
That makes sense. Thanks a ton! I thought I was screwed.

**Comment by SpyrosRoum** [comment]
Hey guys, I am getting the same issue under linux. Weird thing is that when I try `echo $DISPLAY` I get `:0`
