### ISSUE TITLE
Unable to use media keys on Kubuntu 20.04

### ISSUE THREAD

**Issue by varishtsg** [moses-palmer/pynput#313]
While trying to simulate media keys like, volume up / down or play / pause, it simply crashes and gives me this error.

keyboard.press(Key.media_play_pause)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/senpai/.virtualenvs/SunteHo/lib/python3.8/site-packages/pynput/keyboard/_base.py", line 392, in press
    self._handle(resolved, True)
  File "/home/senpai/.virtualenvs/SunteHo/lib/python3.8/site-packages/pynput/keyboard/_xorg.py", line 243, in _handle
    Xlib.ext.xtest.fake_input(
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/home/senpai/.virtualenvs/SunteHo/lib/python3.8/site-packages/pynput/_util/xorg.py", line 78, in display_manager
    raise X11Error(errors)
pynput._util.xorg.X11Error: [(BadValue(<Xlib.display._BaseDisplay object at 0x7fd21822c550>, b'\x00\x02#\x00\x00\x00\x00\x00\x02\x00\x84\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'), None)]

I am running Kubuntu 20.04. I am using a laptop with Nvidia GPU if that helps.

**Comment by SuperMechaDeathChrist** [comment]
I'm experiencing the same error. I'm trying to run a server controlling the mouse and keyboard of a Raspberry Pi 4. The OS is Raspberry OS 10 (buster). I also have a keyboard with multimedia buttons. It doesn't detect play/next/previous in that keyboard, but it does detect volume up/down/mute, so at least volume keys should work.

**Comment by MatthiasLohr** [comment]
Any solution for this so far? Struggling with the same issue... None if the media keys are working, I'm getting the same error as described above.

**Comment by SuperMechaDeathChrist** [comment]
I found a workaround. At least for the volume control keys, anyways. Media play_pause/previous/next still don't work. But that's probably because they also don't wok for my physical keyboard. If there's anyone with linux and multimedia keys working in a physical keyboard, please try this method and report if you can get them to work using pynput.

First, I ran this key logger:
```Python3
from pynput.keyboard import Listener

def log_keystroke(key):
    key = str(key).replace("'", "")

    if key == 'Key.space':
        key = ' '
    if key == 'Key.shift_r':
        key = ''
    if key == "Key.enter":
        key = '\n'
    print(key,[key])

with Listener(on_press=log_keystroke) as l: l.join()
```

and saw what was being printed for the keys that did work for the physical keyboard I had.
This is what I got for the media and volume keys as a dict:

```Python3
myKey = {
    'media_play_pause':269025044,
    'media_volume_mute':269025042,
    'media_volume_down':269025041,
    'media_volume_up':269025043,
    'media_previous':269025046,
    'media_next':269025047,
    }
```
So, when I want to increase the volume on my Raspberry Pi 4, I just do this:
```Python3
from pynput.keyboard import Key, KeyCode, Controller as KeyboardController
keyboard = KeyboardController()

nk=KeyCode(myKey['media_volume_up'])
keyboard.press(nk)
keyboard.release(nk)

# Instead of this, which causes the BadValue error already mentioned.
# keyboard.press(Key.media_volume_up)
# keyboard.release(Key.media_volume_up)
```
I'm not sure if those numeric key codes are dependent on the operating system or what.
Try this method and report your key codes. It might help somebody.

**Comment by moses-palmer** [comment]
Thank you for your investigation!

It appears that the keycodes for media keys may need revisiting.

**Comment by Saruspete** [comment]
Hello,

i'm having the same issue. In my case, the Media buttons are defined in `Xlib/keysymdef/xf86.py`. 
So i'm just chaning in `KeyCode._from_media` the `XF86Audio` to `XF86_Audio`
```
In [1]: from pynput.keyboard import Controller, Key, KeyCode                                                                                                                                           
Xlib.xauth: warning, no xauthority details available

In [2]: Key.media_play_pause                                                                                                                                                                           
Out[2]: <Key.media_play_pause: <269025044>>

In [3]: Key.media_volume_mute                                                                                                                                                                          
Out[3]: <Key.media_volume_mute: <269025042>>
```

**Comment by Saruspete** [comment]
Hello,

Can anyone check if this simple fix (adding an underscore) is working for you too, so we can implement it ? 
@moses-palmer  @MatthiasLohr @SuperMechaDeathChrist 

thanks

**Comment by moses-palmer** [comment]
I have pushed the suggested changes to [fixup-xorg-media-keys](https://github.com/moses-palmer/pynput/tree/fixup-xorg-media-keys).

This updated version does not crash for me, but then again, neither did the previous one. I would appreciate feedback on whether it fixes the problem for you, @varishtsg , @SuperMechaDeathChrist, @MatthiasLohr and @Saruspete.

**Comment by Saruspete** [comment]
Works for me.

Had to struggle to work against the version on the system, but once fixed, that was good. 

You can test this on/off with a sed like 
```
# Comment load line, shouldn't work:
sed -Ee "/^#?Xlib.XK.load_keysym_group/s/^#?/#/" -i lib/python3*/site-packages/pynput/keyboard/_xorg.py
# Uncomment, should work again
sed -Ee "/^#?Xlib.XK.load_keysym_group/s/^#?//" -i lib/python3*/site-packages/pynput/keyboard/_xorg.py
```

**Comment by Saruspete** [comment]
Hello OP & commenters @varishtsg @SuperMechaDeathChrist @MatthiasLohr

Can you please test the branch with fixes done by @moses-palmer so they can merge it ?

Thanks

**Comment by MatthiasLohr** [comment]
Sorry for my late reply. I'l try as soon as I can. What I can confirm for now: Just using the keycode numbers presented by @SuperMechaDeathChrist, it works for me. But I didn't take a look at the exact other changes, so I can't give a statement for that right now.

**Comment by Saruspete** [comment]
Hello & Happy new year,

No news from anybody else here, despite the work done by @moses-palmer ... Let's get this fork merged

Cheers,

**Comment by BETLOG** [comment]
Kubuntu 22.04 and this seems to have resurfaced somewhere prior to about 2023-05-01(+10UTC)
108 keyboard (only has volume buttons), and the following have stopped working: mute, volume up, volume down

`xev`

`KeyRelease event, serial 40, synthetic NO, window 0x6e00001,
    root 0x1e3, subw 0x0, time 3429709, (271,227), root:(1142,725),
    state 0x10, keycode 121 (keysym 0x1008ff12, XF86AudioMute), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False`

`KeyRelease event, serial 40, synthetic NO, window 0x6e00001,
    root 0x1e3, subw 0x0, time 3430175, (271,227), root:(1142,725),
    state 0x10, keycode 122 (keysym 0x1008ff11, XF86AudioLowerVolume), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False`

`KeyRelease event, serial 40, synthetic NO, window 0x6e00001,
    root 0x1e3, subw 0x0, time 3430639, (271,227), root:(1142,725),
    state 0x10, keycode 123 (keysym 0x1008ff13, XF86AudioRaiseVolume), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False`

`sudo showkey -k`

`keycode  28 release
keycode 113 press
keycode 113 release
keycode 114 press
keycode 114 release
keycode 115 press
keycode 115 release`
