### ISSUE TITLE
Module not found: pynput

### ISSUE THREAD

**Issue by malwguy** [moses-palmer/pynput#402]
**Description**
Pyinstaller won't import my pynput module

**Platform and pynput version**
pynput's version is already backed to 1.6.8, I tried to import it with hidden-import yet no success. 

This is what debug=all shows me : 
Traceback (most recent call last):
  File "WindowsDefender.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pynput'

The command I used is :   pyinstaller --onefile --noconsole --debug=all --hidden-import="pynput.keyboard._win32" --clean WindowsDefender.py

And I only have imported pynput.keyboard, not the whole module.

**Comment by moses-palmer** [comment]
Thank you for your report.

This does not seem like an issue with this library, so I will close this ticket. If you think this is incorrect, please reopen.
