### ISSUE TITLE
AttributeError: dlsym(0x3a0604b58, objc_msgSendSuper_stret): symbol not found

### ISSUE THREAD

**Issue by monkey410** [moses-palmer/pynput#553]
Help！！！！
My operating system and version：Ventura13.0，M1,

**The error message is as follows:**

Traceback (most recent call last):
  File "/Users/jxtech-liu/Desktop/demo/Code/demo.py", line 3, in <module>
    import pyautogui
  File "/opt/homebrew/lib/python3.8/site-packages/pyautogui/__init__.py", line 249, in <module>
    import mouseinfo
  File "/opt/homebrew/lib/python3.8/site-packages/mouseinfo/__init__.py", line 100, in <module>
    from rubicon.objc import ObjCClass, CGPoint
  File "/opt/homebrew/lib/python3.8/site-packages/rubicon/objc/__init__.py", line 33, in <module>
    from . import api, collections, runtime, types
  File "/opt/homebrew/lib/python3.8/site-packages/rubicon/objc/api.py", line 28, in <module>
    from .runtime import (
  File "/opt/homebrew/lib/python3.8/site-packages/rubicon/objc/runtime.py", line 460, in <module>
    libobjc.objc_msgSendSuper_stret.restype = None
  File "/opt/homebrew/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/opt/homebrew/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
**AttributeError: dlsym(0x3a0604b58, objc_msgSendSuper_stret): symbol not found**

**Comment by monkey410** [comment]
Refer to similar questions：https://github.com/moses-palmer/pynput/issues/420
Lowering the pyobjc version to 7.3 (or the latest version) will not work

**Comment by moses-palmer** [comment]
Thank you for your report.

...but I cannot find *pynput* anywhere in the stack trace provided, and the error appears to be in *pyobjc*. I will close this issue, but if it actually is related to this library, please reopen.
