### ISSUE TITLE
click theRunIsStuck

### ISSUE THREAD

**Issue by chenyuxingkong** [moses-palmer/pynput#613]
```import pynput
from pynput import mouse
from pynput.mouse import Button

isRun = False
ctr = pynput.mouse.Controller()


def g36k():
    global isRun
    isRun = True
    print("start")
    # 运行卡死
    # theRunIsStuck
    ctr.click(Button.left)
    print("end")


def on_click(x, y, button, pressed):
    print(f'鼠标按下: {button} at ({x}, {y})')
    global isRun
    # 鼠标松开时触发
    if not pressed:
        if button == Button.x1 and not isRun:
            # 将 g36k 的调用调度到事件循环
            g36k()
            isRun = False


if __name__ == '__main__':
    # 创建鼠标监听器
    listener = mouse.Listener(on_click=on_click)
    listener.start()
    listener.join()
```
The above is my py code. When I run to ctr.click(Button.left), I can't output print("end "), and my mouse is stuck.

**Comment by moses-palmer** [comment]
Thank you for your report.

As you do not state what platform you are running this on I can only speculate. However, I think the issue is that these functions are not invoked sequentially; when a mouse button is clicked, `on_click` is eventually called and the check whether `isRun` is `True` is performed. Since it is not, `g36k` is called, a fake event is emitted and `isRun` is reset to `False`. Some time later, the fake event will cause `on_click` to be called again, but `isRun` has already been reset.

I suggest you check out the [`feature-injected`](https://github.com/moses-palmer/pynput/tree/feature-injected) branch. On that branch, you get an extra argument to `on_click`: `injected`. This argument signals that the current event was not generated by the user, but rather some other controller; this appears to be what you are after.

I would love some feedback on that branch; it has remained unmerged for six years already, but I have at least kept it up-to-date.

**Comment by abrichr** [comment]
@moses-palmer thank you for keeping it up to date. However using that branch on MacOS 14.2.1 Python 3.10.9 I am getting:
```
Unhandled exception in listener callback                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                         
  File "/Users/abrichr/Library/Caches/pypoetry/virtualenvs/openadapt-VeocdZtQ-py3.10/lib/python3.10/site-packages/pynput/_util/__init__.py", line 230, in inner
    return f(self, *args, **kwargs)                                                                                                                                                        
  File "/Users/abrichr/Library/Caches/pypoetry/virtualenvs/openadapt-VeocdZtQ-py3.10/lib/python3.10/site-packages/pynput/_util/darwin.py", line 284, in _handler
    is_injected = (Quartz.CGEventGetIntegerValueField(                                                                                                                                     
NameError: name 'Quartz' is not defined
```
To fix:

1. 
https://github.com/moses-palmer/pynput/blob/feature-injected/lib/pynput/_util/darwin.py#L43 should have:
```
CGEventGetIntegerValueField,
kCGEventSourceUnixProcessID
```

2.
https://github.com/moses-palmer/pynput/blob/feature-injected/lib/pynput/_util/darwin.py#L284 should be
```
        is_injected = (CGEventGetIntegerValueField(
            event,
            kCGEventSourceUnixProcessID)) != 0
```

**Comment by moses-palmer** [comment]
@abrichr 

Thank you very much for your fix! I have updated the feature branch with your suggestion.
