### ISSUE TITLE
"TypeError: '_thread._ThreadHandle' object is not callable" while using python 3.13.1

### ISSUE THREAD

**Issue by EricCart** [moses-palmer/pynput#620]
**Description**
Python 3.11.5 works fine. Python 3.13.1 won't work with example code
```python
from pynput import keyboard

def on_press(key):
    print(f'Key pressed: {key}')

def on_release(key):
    if key == keyboard.Key.esc:
        # Stop listener
        return False

# Collect events until released
with keyboard.Listener(on_press=on_press, on_release=on_release) as listener:
    listener.join()
```
**Platform and pynput version**
Pynput version: 1.7.6
Platform: Macos 15.3 Beta

**Comment by xtremforce** [comment]
same issue here

**Comment by MatheusMartins** [comment]
Running Python 3.13.1 I had a very similar error message:

```
Unhandled exception in listener callback
Traceback (most recent call last):
  File "~/project/.venv/lib/python3.13/site-packages/pynput/_util/__init__.py", line 229, in inner
    return f(self, *args, **kwargs)
  File "~/project/.venv/lib/python3.13/site-packages/pynput/_util/darwin.py", line 283, in _handler
    self._handle(proxy, event_type, event, refcon)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '_thread._ThreadHandle' object is not callable
```

Worked around ok using python 3.12.5 via pyenv

**Comment by felixthibault** [comment]
I had exactly the same issue. You're saying that's linked to the listener callback? I thought it was linked to the threading process I had in a class, but there's nothing talking about the name of the thread. The whole code was working greatly some months ago on windows python ~2.7 with threading and listener and instance.
`Unhandled exception in listener callback
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/pynput/_util/__init__.py", line 229, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.13/site-packages/pynput/_util/xorg.py", line 470, in _handler
    self._handle(self._display_stop, event)
      ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^`

**Comment by TonyN678** [comment]
I encountered this problem today as well, is there any fix or workaround? 
(I turned to pynput to bypass root privilege in keyboard library)

**Comment by toddwint** [comment]
I am also experiencing this issue.

Operating System: Ubuntu 24.04.1 LTS
pynput 1.7.7
Python 3.13.1

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "~/.local/.venv/python3.13/lib/python3.13/site-packages/pynput/_util/__init__.py", line 211, in run
    self._run()
    ~~~~~~~~~^^
  File "~/.local/.venv/python3.13/lib/python3.13/site-packages/pynput/_util/uinput.py", line 55, in _run
    self._handle(event)
    ~~~~~~~~~~~~^^^^^^^
TypeError: '_thread._ThreadHandle' object is not callable
```

**Comment by ivfiev** [comment]
Same here
Python 3.13.1
```
Unhandled exception in listener callback
Traceback (most recent call last):
  File "/home/.../.venv/lib/python3.13/site-packages/pynput/_util/__init__.py", line 229, in inner
    return f(self, *args, **kwargs)
  File "/home/.../.venv/lib/python3.13/site-packages/pynput/_util/xorg.py", line 470, in _handler
    self._handle(self._display_stop, event)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '_thread._ThreadHandle' object is not callable
```

**Comment by felixthibault** [comment]
Maybe wait for new release of pynput or try a older version of python in an environnement.

**Comment by moses-palmer** [comment]
Thank you for your report.

I will close this issue, as it is a duplicate of #614. Please see [`fixup/listener-thread-handle`](https://github.com/moses-palmer/pynput/tree/fixup/listener-thread-handle) for a proposed solution.
