### ISSUE TITLE
type(str) fails when str contains \t

### ISSUE THREAD

**Issue by woky** [moses-palmer/pynput#95]
`emulatekb` script:

    #!/usr/bin/env python3

    import sys
    from pynput.keyboard import Key, Controller

    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} TEXT")
        sys.exit(1)

    kb = Controller()
    kb.type(sys.argv[1])

Trying to type a string with `\t` character:

    % ./emulatekb gc$'\t'c
    gcTraceback (most recent call last):
      File "/home/woky/.local/lib/python3.6/site-packages/pynput/keyboard/_base.py", line 450, in type
        self.release(character)
      File "/home/woky/.local/lib/python3.6/site-packages/pynput/keyboard/_base.py", line 404, in release
        self._handle(resolved, False)
      File "/home/woky/.local/lib/python3.6/site-packages/pynput/keyboard/_xorg.py", line 196, in _handle
        raise self.InvalidKeyException(key)
    pynput.keyboard._base.InvalidKeyException: '\t'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "./emulatekb", line 11, in <module>
        kb.type(sys.argv[1])
      File "/home/woky/.local/lib/python3.6/site-packages/pynput/keyboard/_base.py", line 453, in type
        raise self.InvalidCharacterException(i, character)
    pynput.keyboard._base.InvalidCharacterException: (4, '\t')

As space corresponds to `Key.space`, `\t` should correspond to `Key.tab`. Perhaps also `\n` should correspond to `Key.enter`.

**Comment by moses-palmer** [comment]
This was supposedly fixed in commit [4afea36](https://github.com/moses-palmer/pynput/commit/4afea360635d26f5a61a9bc9ee05e88a7be0a643). Can you test running the matter branch?

**Comment by moses-palmer** [comment]
I will close this issue now. Please reopen if the error persists.
