### ISSUE TITLE
setup.py fails with Python 2

### ISSUE THREAD

**Issue by j4321** [moses-palmer/pynput#96]
When I do ``python2 setup.py sdist`` (or ``install``), I get the following error:

```
Traceback (most recent call last):
  File "setup.py", line 123, in <module>
    'Topic :: System :: Monitoring'])
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 128, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 514, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 770, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1053, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 581, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 699, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 884, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1152, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1140, in run_setup
    raise DistutilsError("Setup script exited with %s" % (v.args[0],))
distutils.errors.DistutilsError: Setup script exited with Error: typed_ast only runs on Python 3.3 and above.
```

I am using Archlinux and:

- python 2.7.15,
- xlib 0.23, 
- setuptools 39.2.0, 
- six 1.11.0

**Comment by moses-palmer** [comment]
Thank you for your report.

Do you have any steps to reproduce this error? I have attempted with
```bash
python2.7 -m virtualenv venv/linux-2.7
. venv/linux-2.7/bin/activate
python setup.py develop # or pip install pynput
```

I can confirm that `pip install typed_ast` fails when running under _Python 2.7_, but my system does not attempt to install it.
